name:                judge-hs
version:             0.1.0.0
github:              "nobsun/judge-hs"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2022 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/judge-hs#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- hspec
- directory
- filepath
- process

library:
  source-dirs: src

executables:
  judge-hs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - judge-hs

tests:
  judge-hs-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - judge-hs
    - hspec
    - main-tester

  judge-hs-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - judge-hs
    - doctest
